/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tw.elliot.backend;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
    }
}
